language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test 

after_success:
  - docker build -t jenny0707/multi-client ./client
  - docker build -t jenny0707/multi-nginx ./nginx
  - docker build -t jenny0707/multi-server ./server
  - docker build -t jenny0707/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jenny0707/multi-client
  - docker push jenny0707/multi-nginx
  - docker push jenny0707/multi-server
  - docker push jenny0707/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-873252473428"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
